export const EMPLOYEEDEATAILS_INPROGRESS = 'EMPLOYEEDEATAILS_INPROGRESS';
export const EMPLOYEEDEATAILS_SUCCESS = 'EMPLOYEEDEATAILS_SUCCESS';
export const EMPLOYEEDEATAILS_ERROR = 'EMPLOYEEDEATAILS_ERROR';